# Generated by Django 5.1.1 on 2024-10-18 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='model_limit',
            field=models.JSONField(default=list, verbose_name='备注'),
        ),
    ]
