# Generated by Django 5.1.1 on 2024-11-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_model_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expired_date',
            field=models.DateField(blank=True, null=True, verbose_name='过期日期'),
        ),
    ]
