# Generated by Django 5.1.1 on 2024-10-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgptcar',
            name='created_time',
            field=models.IntegerField(blank=True, db_index=True, default=1, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatgptcar',
            name='updated_time',
            field=models.IntegerField(blank=True, db_index=True, default=1, verbose_name='最后修改时间'),
            preserve_default=False,
        ),
    ]
